##### import pandas,numpy

In [1]:
import pandas as pd
import numpy as np

##### Loading CSV File

In [2]:
supply_chain = pd.read_csv('dynamic_supply_chain_logistics_dataset.csv')

In [3]:
supply_chain.head()

,timestamp,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,...,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation
0,2021-01-01 00:00:00,40.375568,-77.014318,5.136512,4.998009,5.927586,985.716862,4.951392,0.481294,0.761166,...,0.574400,0.777263,1.182116,0.502006,0.033843,0.978599,0.506152,0.885291,Moderate Risk,9.110682
1,2021-01-01 01:00:00,33.507818,-117.036902,5.101512,0.984929,1.591992,396.700206,1.030379,0.620780,0.196594,...,-9.753493,0.091839,9.611988,0.966774,0.201725,0.918586,0.980784,0.544178,High Risk,8.175281
2,2021-01-01 02:00:00,30.020640,-75.269224,5.090803,4.972665,8.787765,832.408935,4.220229,0.810933,0.152742,...,-6.491034,0.253529,6.570431,0.945627,0.264045,0.394215,0.998633,0.803322,High Risk,1.283594
3,2021-01-01 03:00:00,36.649223,-70.190529,8.219558,3.095064,0.045257,0.573283,0.530186,0.008525,0.811885,...,-0.151276,0.877576,0.548952,4.674035,0.362885,0.905444,0.993320,0.025977,High Risk,9.304897
4,2021-01-01 04:00:00,30.001279,-70.012195,5.000075,3.216077,8.004851,914.925067,3.620890,0.020083,0.053659,...,2.429448,0.262081,8.861443,3.445429,0.016957,0.258702,0.912433,0.991122,High Risk,7.752484

In [4]:
supply_chain.columns

Index(['timestamp', 'vehicle_gps_latitude', 'vehicle_gps_longitude',
       'fuel_consumption_rate', 'eta_variation_hours',
       'traffic_congestion_level', 'warehouse_inventory_level',
       'loading_unloading_time', 'handling_equipment_availability',
       'order_fulfillment_status', 'weather_condition_severity',
       'port_congestion_level', 'shipping_costs', 'supplier_reliability_score',
       'lead_time_days', 'historical_demand', 'iot_temperature',
       'cargo_condition_status', 'route_risk_level', 'customs_clearance_time',
       'driver_behavior_score', 'fatigue_monitoring_score',
       'disruption_likelihood_score', 'delay_probability',
       'risk_classification', 'delivery_time_deviation'],
      dtype='str')

##### Divide data into df_transit,df_warehouse,df_risk based on the nature of column

In [5]:
df_transit = supply_chain[['timestamp', 'vehicle_gps_latitude', 'vehicle_gps_longitude',
       'fuel_consumption_rate', 'eta_variation_hours',
       'traffic_congestion_level','delivery_time_deviation',
                          'shipping_costs','order_fulfillment_status']]

In [6]:
df_warehouse = supply_chain[['warehouse_inventory_level',
       'loading_unloading_time', 'handling_equipment_availability'
       ,'supplier_reliability_score','lead_time_days', 'historical_demand',
       'disruption_likelihood_score', 'delay_probability', 'customs_clearance_time']]

In [7]:
df_risk = supply_chain[['weather_condition_severity',
       'port_congestion_level','iot_temperature',
       'cargo_condition_status', 'route_risk_level','risk_classification']]

In [8]:
start_id = 1021

df_transit['record_id'] = range(start_id,start_id+len(df_transit))
df_warehouse['logistics_id'] = range(start_id, start_id+len(df_transit))
df_risk['shipment_id'] = range(start_id, start_id+len(df_risk))

In [9]:
df_transit.head()

,timestamp,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,delivery_time_deviation,shipping_costs,order_fulfillment_status,record_id
0,2021-01-01 00:00:00,40.375568,-77.014318,5.136512,4.998009,5.927586,9.110682,456.503853,0.761166,1021
1,2021-01-01 01:00:00,33.507818,-117.036902,5.101512,0.984929,1.591992,8.175281,640.408205,0.196594,1022
2,2021-01-01 02:00:00,30.020640,-75.269224,5.090803,4.972665,8.787765,1.283594,155.749314,0.152742,1023
3,2021-01-01 03:00:00,36.649223,-70.190529,8.219558,3.095064,0.045257,9.304897,104.317961,0.811885,1024
4,2021-01-01 04:00:00,30.001279,-70.012195,5.000075,3.216077,8.004851,7.752484,977.222528,0.053659,1025

##### Data Cleaning and Analysing for df_transit

In [10]:
df_transit.info()

<class 'pandas.DataFrame'>
RangeIndex: 32065 entries, 0 to 32064
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   timestamp                 32065 non-null  str
 1   vehicle_gps_latitude      32065 non-null  float64
 2   vehicle_gps_longitude     32065 non-null  float64
 3   fuel_consumption_rate     32065 non-null  float64
 4   eta_variation_hours       32065 non-null  float64
 5   traffic_congestion_level  32065 non-null  float64
 6   delivery_time_deviation   32065 non-null  float64
 7   shipping_costs            32065 non-null  float64
 8   order_fulfillment_status  32065 non-null  float64
 9   record_id                 32065 non-null  int64
dtypes: float64(8), int64(1), str(1)
memory usage: 2.4 MB

In [11]:
df_transit.isnull().sum()

timestamp                   0
vehicle_gps_latitude        0
vehicle_gps_longitude       0
fuel_consumption_rate       0
eta_variation_hours         0
traffic_congestion_level    0
delivery_time_deviation     0
shipping_costs              0
order_fulfillment_status    0
record_id                   0
dtype: int64

In [12]:
df_transit['timestamp'] = pd.to_datetime(df_transit['timestamp'])

In [13]:
df_transit.columns

Index(['timestamp', 'vehicle_gps_latitude', 'vehicle_gps_longitude',
       'fuel_consumption_rate', 'eta_variation_hours',
       'traffic_congestion_level', 'delivery_time_deviation', 'shipping_costs',
       'order_fulfillment_status', 'record_id'],
      dtype='str')

In [14]:
df_transit =df_transit.rename(columns={
                            'vehicle_gps_latitude' : 'latitude'
                           , 'vehicle_gps_longitude': "longitude"
                           , 'fuel_consumption_rate': "fuel_rate"
                           , 'eta_variation_hours' : "eta_vars_hrs"
                           , 'traffic_congestion_level' : "traffic_level"
                           , 'delivery_time_deviation' : "time_deviation"
                           , 'order_fulfillment_status' : "order_status"
})

In [15]:
df_transit.head()

,timestamp,latitude,longitude,fuel_rate,eta_vars_hrs,traffic_level,time_deviation,shipping_costs,order_status,record_id
0,2021-01-01 00:00:00,40.375568,-77.014318,5.136512,4.998009,5.927586,9.110682,456.503853,0.761166,1021
1,2021-01-01 01:00:00,33.507818,-117.036902,5.101512,0.984929,1.591992,8.175281,640.408205,0.196594,1022
2,2021-01-01 02:00:00,30.020640,-75.269224,5.090803,4.972665,8.787765,1.283594,155.749314,0.152742,1023
3,2021-01-01 03:00:00,36.649223,-70.190529,8.219558,3.095064,0.045257,9.304897,104.317961,0.811885,1024
4,2021-01-01 04:00:00,30.001279,-70.012195,5.000075,3.216077,8.004851,7.752484,977.222528,0.053659,1025

In [16]:
df_transit.info()

<class 'pandas.DataFrame'>
RangeIndex: 32065 entries, 0 to 32064
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       32065 non-null  datetime64[us]
 1   latitude        32065 non-null  float64
 2   longitude       32065 non-null  float64
 3   fuel_rate       32065 non-null  float64
 4   eta_vars_hrs    32065 non-null  float64
 5   traffic_level   32065 non-null  float64
 6   time_deviation  32065 non-null  float64
 7   shipping_costs  32065 non-null  float64
 8   order_status    32065 non-null  float64
 9   record_id       32065 non-null  int64
dtypes: datetime64[us](1), float64(8), int64(1)
memory usage: 2.4 MB

In [17]:
df_transit['traffic_level'] = df_transit['traffic_level'].astype(int)

In [18]:
df_transit['date'] = df_transit['timestamp'].dt.date
df_transit['time'] = df_transit['timestamp'].dt.time

In [19]:
df_transit.drop(columns =['timestamp'], inplace=True)

In [20]:
df_transit.columns

Index(['latitude', 'longitude', 'fuel_rate', 'eta_vars_hrs', 'traffic_level',
       'time_deviation', 'shipping_costs', 'order_status', 'record_id', 'date',
       'time'],
      dtype='str')

In [21]:
df_transit.head(2)

,latitude,longitude,fuel_rate,eta_vars_hrs,traffic_level,time_deviation,shipping_costs,order_status,record_id,date,time
0,40.375568,-77.014318,5.136512,4.998009,5,9.110682,456.503853,0.761166,1021,2021-01-01,00:00:00
1,33.507818,-117.036902,5.101512,0.984929,1,8.175281,640.408205,0.196594,1022,2021-01-01,01:00:00

In [22]:
print(df_transit['time'])

0        00:00:00
1        01:00:00
2        02:00:00
3        03:00:00
4        04:00:00
           ...
32060    20:00:00
32061    21:00:00
32062    22:00:00
32063    23:00:00
32064    00:00:00
Name: time, Length: 32065, dtype: object

In [23]:
df_transit.rename(columns = {'shipping_costs' :'shipping_cost_usd'
                                                          ,'fuel_rate' : 'fuel_rate_usd'}, inplace=True)

In [24]:
# Yeh command apne aap check karegi aur saare empty columns ko uda degi
df_transit.dropna(axis=1, how='all', inplace=True)

In [25]:
df_transit.head()

,latitude,longitude,fuel_rate_usd,eta_vars_hrs,traffic_level,time_deviation,shipping_cost_usd,order_status,record_id,date,time
0,40.375568,-77.014318,5.136512,4.998009,5,9.110682,456.503853,0.761166,1021,2021-01-01,00:00:00
1,33.507818,-117.036902,5.101512,0.984929,1,8.175281,640.408205,0.196594,1022,2021-01-01,01:00:00
2,30.020640,-75.269224,5.090803,4.972665,8,1.283594,155.749314,0.152742,1023,2021-01-01,02:00:00
3,36.649223,-70.190529,8.219558,3.095064,0,9.304897,104.317961,0.811885,1024,2021-01-01,03:00:00
4,30.001279,-70.012195,5.000075,3.216077,8,7.752484,977.222528,0.053659,1025,2021-01-01,04:00:00

In [26]:
df_transit.columns

Index(['latitude', 'longitude', 'fuel_rate_usd', 'eta_vars_hrs',
       'traffic_level', 'time_deviation', 'shipping_cost_usd', 'order_status',
       'record_id', 'date', 'time'],
      dtype='str')

In [27]:
cols = ['fuel_rate_usd', 'eta_vars_hrs', 'traffic_level', 'time_deviation', 'shipping_cost_usd', 'order_status']

In [28]:
df_transit[cols] =df_transit[cols].round(2)

In [29]:
df_transit.head()

,latitude,longitude,fuel_rate_usd,eta_vars_hrs,traffic_level,time_deviation,shipping_cost_usd,order_status,record_id,date,time
0,40.375568,-77.014318,5.14,5.00,5,9.11,456.50,0.76,1021,2021-01-01,00:00:00
1,33.507818,-117.036902,5.10,0.98,1,8.18,640.41,0.20,1022,2021-01-01,01:00:00
2,30.020640,-75.269224,5.09,4.97,8,1.28,155.75,0.15,1023,2021-01-01,02:00:00
3,36.649223,-70.190529,8.22,3.10,0,9.30,104.32,0.81,1024,2021-01-01,03:00:00
4,30.001279,-70.012195,5.00,3.22,8,7.75,977.22,0.05,1025,2021-01-01,04:00:00

##### Data Cleaning and Analysing for df_warehouse

In [30]:
df_warehouse.head(2)

,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,supplier_reliability_score,lead_time_days,historical_demand,disruption_likelihood_score,delay_probability,customs_clearance_time,logistics_id
0,985.716862,4.951392,0.481294,0.986064,2.128009,100.772854,0.506152,0.885291,0.502006,1021
1,396.700206,1.030379,0.620780,0.463233,12.608166,5313.738114,0.980784,0.544178,0.966774,1022

In [31]:
df_warehouse.columns

Index(['warehouse_inventory_level', 'loading_unloading_time',
       'handling_equipment_availability', 'supplier_reliability_score',
       'lead_time_days', 'historical_demand', 'disruption_likelihood_score',
       'delay_probability', 'customs_clearance_time', 'logistics_id'],
      dtype='str')

In [32]:
df_warehouse.rename(columns ={ 
    'warehouse_inventory_level' : 'inventory_level_units', 
    'loading_unloading_time' : 'load_unload_hrs',
    'handling_equipment_availability' : 'equipment_availability_percent', 
    'supplier_reliability_score' : 'supplier_reliability', 
    'disruption_likelihood_score' : 'disruption_likelihood',
    'customs_clearance_time' : 'customs_days',
    'historical_demand':'historical_demand_units',
    'lead_time_days':'lead_days'
}, inplace=True)

In [33]:
df_warehouse.columns

Index(['inventory_level_units', 'load_unload_hrs',
       'equipment_availability_percent', 'supplier_reliability', 'lead_days',
       'historical_demand_units', 'disruption_likelihood', 'delay_probability',
       'customs_days', 'logistics_id'],
      dtype='str')

In [34]:
cols = ['inventory_level_units', 'load_unload_hrs',
       'equipment_availability_percent', 'supplier_reliability', 'lead_days',
       'historical_demand_units', 'disruption_likelihood', 'delay_probability',
       'customs_days', 'logistics_id']
df_warehouse[cols] = df_warehouse[cols].round(2)

In [35]:
df_warehouse.head()

,inventory_level_units,load_unload_hrs,equipment_availability_percent,supplier_reliability,lead_days,historical_demand_units,disruption_likelihood,delay_probability,customs_days,logistics_id
0,985.72,4.95,0.48,0.99,2.13,100.77,0.51,0.89,0.50,1021
1,396.70,1.03,0.62,0.46,12.61,5313.74,0.98,0.54,0.97,1022
2,832.41,4.22,0.81,0.60,14.12,1595.05,1.00,0.80,0.95,1023
3,0.57,0.53,0.01,0.74,3.82,2530.43,0.99,0.03,4.67,1024
4,914.93,3.62,0.02,0.43,14.00,2146.19,0.91,0.99,3.45,1025

In [36]:
df_warehouse.isnull().sum()

inventory_level_units             0
load_unload_hrs                   0
equipment_availability_percent    0
supplier_reliability              0
lead_days                         0
historical_demand_units           0
disruption_likelihood             0
delay_probability                 0
customs_days                      0
logistics_id                      0
dtype: int64

In [37]:
df_warehouse.head()

,inventory_level_units,load_unload_hrs,equipment_availability_percent,supplier_reliability,lead_days,historical_demand_units,disruption_likelihood,delay_probability,customs_days,logistics_id
0,985.72,4.95,0.48,0.99,2.13,100.77,0.51,0.89,0.50,1021
1,396.70,1.03,0.62,0.46,12.61,5313.74,0.98,0.54,0.97,1022
2,832.41,4.22,0.81,0.60,14.12,1595.05,1.00,0.80,0.95,1023
3,0.57,0.53,0.01,0.74,3.82,2530.43,0.99,0.03,4.67,1024
4,914.93,3.62,0.02,0.43,14.00,2146.19,0.91,0.99,3.45,1025

In [38]:
df_warehouse.info()

<class 'pandas.DataFrame'>
RangeIndex: 32065 entries, 0 to 32064
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   inventory_level_units           32065 non-null  float64
 1   load_unload_hrs                 32065 non-null  float64
 2   equipment_availability_percent  32065 non-null  float64
 3   supplier_reliability            32065 non-null  float64
 4   lead_days                       32065 non-null  float64
 5   historical_demand_units         32065 non-null  float64
 6   disruption_likelihood           32065 non-null  float64
 7   delay_probability               32065 non-null  float64
 8   customs_days                    32065 non-null  float64
 9   logistics_id                    32065 non-null  int64
dtypes: float64(9), int64(1)
memory usage: 2.4 MB

In [39]:
df_transit

,latitude,longitude,fuel_rate_usd,eta_vars_hrs,traffic_level,time_deviation,shipping_cost_usd,order_status,record_id,date,time
0,40.375568,-77.014318,5.14,5.00,5,9.11,456.50,0.76,1021,2021-01-01,00:00:00
1,33.507818,-117.036902,5.10,0.98,1,8.18,640.41,0.20,1022,2021-01-01,01:00:00
2,30.020640,-75.269224,5.09,4.97,8,1.28,155.75,0.15,1023,2021-01-01,02:00:00
3,36.649223,-70.190529,8.22,3.10,0,9.30,104.32,0.81,1024,2021-01-01,03:00:00
4,30.001279,-70.012195,5.00,3.22,8,7.75,977.22,0.05,1025,2021-01-01,04:00:00
...,...,...,...,...,...,...,...,...,...,...,...
32060,48.496665,-104.031158,5.42,4.39,0,5.51,413.26,0.99,33081,2024-08-28,20:00:00
32061,34.670137,-89.893091,10.62,2.70,8,-1.88,243.31,0.95,33082,2024-08-28,21:00:00
32062,42.963338,-82.149873,5.07,0.49,7,9.79,722.12,0.44,33083,2024-08-28,22:00:00
32063,32.082410,-70.070154,5.00,4.76,0,9.96,484.50,0.52,33084,2024-08-28,23:00:00
32064,38.576482,-94.579542,5.00,4.07,7,2.10,202.23,0.99,33085,2024-08-29,00:00:00

In [40]:
df_risk.head()

,weather_condition_severity,port_congestion_level,iot_temperature,cargo_condition_status,route_risk_level,risk_classification,shipment_id
0,0.359066,4.289160,0.574400,0.777263,1.182116,Moderate Risk,1021
1,0.230660,7.018373,-9.753493,0.091839,9.611988,High Risk,1022
2,0.027210,9.605064,-6.491034,0.253529,6.570431,High Risk,1023
3,0.616619,8.899616,-0.151276,0.877576,0.548952,High Risk,1024
4,0.952385,0.061760,2.429448,0.262081,8.861443,High Risk,1025

In [41]:
df_transit.columns

Index(['latitude', 'longitude', 'fuel_rate_usd', 'eta_vars_hrs',
       'traffic_level', 'time_deviation', 'shipping_cost_usd', 'order_status',
       'record_id', 'date', 'time'],
      dtype='str')

In [42]:
desired_order = ['record_id',
                 'date', 
                 'time', 
                 'latitude', 
                 'longitude', 
                 'fuel_rate_usd', 
                 'eta_vars_hrs',
                 'traffic_level', 
                 'time_deviation',
                 'shipping_cost_usd',
                 'order_status'
        ]

df_transit = df_transit[desired_order]

In [43]:
df_transit.reset_index(inplace=True)

In [44]:
df_transit.columns

Index(['index', 'record_id', 'date', 'time', 'latitude', 'longitude',
       'fuel_rate_usd', 'eta_vars_hrs', 'traffic_level', 'time_deviation',
       'shipping_cost_usd', 'order_status'],
      dtype='str')

In [45]:
df_warehouse.columns

Index(['inventory_level_units', 'load_unload_hrs',
       'equipment_availability_percent', 'supplier_reliability', 'lead_days',
       'historical_demand_units', 'disruption_likelihood', 'delay_probability',
       'customs_days', 'logistics_id'],
      dtype='str')

In [46]:
cols =['logistics_id','inventory_level_units', 'load_unload_hrs',
       'equipment_availability_percent', 'supplier_reliability', 'lead_days',
       'historical_demand_units', 'disruption_likelihood', 'delay_probability',
       'customs_days']
df_warehouse = df_warehouse[cols]

In [47]:
df_warehouse.head()

,logistics_id,inventory_level_units,load_unload_hrs,equipment_availability_percent,supplier_reliability,lead_days,historical_demand_units,disruption_likelihood,delay_probability,customs_days
0,1021,985.72,4.95,0.48,0.99,2.13,100.77,0.51,0.89,0.50
1,1022,396.70,1.03,0.62,0.46,12.61,5313.74,0.98,0.54,0.97
2,1023,832.41,4.22,0.81,0.60,14.12,1595.05,1.00,0.80,0.95
3,1024,0.57,0.53,0.01,0.74,3.82,2530.43,0.99,0.03,4.67
4,1025,914.93,3.62,0.02,0.43,14.00,2146.19,0.91,0.99,3.45

##### Data Cleaning and Analysing for df_risk

In [48]:
df_risk.columns

Index(['weather_condition_severity', 'port_congestion_level',
       'iot_temperature', 'cargo_condition_status', 'route_risk_level',
       'risk_classification', 'shipment_id'],
      dtype='str')

In [49]:
columns =['weather_condition_severity', 'port_congestion_level',
       'iot_temperature', 'cargo_condition_status', 'route_risk_level',
       'risk_classification', 'shipment_id']
if 'index' in df_risk.columns and 'record_id' in df_risk.columns:
    df_risk = df_risk.drop(columns =['index'])

In [50]:
cols = ['weather_condition_severity', 'port_congestion_level',
       'iot_temperature', 'cargo_condition_status', 'route_risk_level',
       'risk_classification']

In [51]:
df_risk[cols] = df_risk[cols].round(2)

In [52]:
df_risk.head()

,weather_condition_severity,port_congestion_level,iot_temperature,cargo_condition_status,route_risk_level,risk_classification,shipment_id
0,0.36,4.29,0.57,0.78,1.18,Moderate Risk,1021
1,0.23,7.02,-9.75,0.09,9.61,High Risk,1022
2,0.03,9.61,-6.49,0.25,6.57,High Risk,1023
3,0.62,8.90,-0.15,0.88,0.55,High Risk,1024
4,0.95,0.06,2.43,0.26,8.86,High Risk,1025

In [53]:
df_risk.dtypes

weather_condition_severity    float64
port_congestion_level         float64
iot_temperature               float64
cargo_condition_status        float64
route_risk_level              float64
risk_classification               str
shipment_id                     int64
dtype: object

In [54]:
df_risk.rename(columns= 
               {
                  'weather_condition_severity' : 'weather_severity',
                  'port_congestion_level' : 'port_cong',
                   'iot_temperature' : 'iot_temp',
                   'cargo_condition_status': 'cargo_status', 
                   'route_risk_level' : 'route_risk',
                   'risk_classification' : 'risk_class',  
               }, inplace=True)

In [55]:
cols = ['shipment_id','weather_severity', 'port_cong', 'iot_temp', 'cargo_status',
       'route_risk', 'risk_class']
df_risk = df_risk[cols]

In [56]:
df_risk = df_risk.drop(columns=['Unnamed:0'], errors='ignore')

In [57]:
df_risk

,shipment_id,weather_severity,port_cong,iot_temp,cargo_status,route_risk,risk_class
0,1021,0.36,4.29,0.57,0.78,1.18,Moderate Risk
1,1022,0.23,7.02,-9.75,0.09,9.61,High Risk
2,1023,0.03,9.61,-6.49,0.25,6.57,High Risk
3,1024,0.62,8.90,-0.15,0.88,0.55,High Risk
4,1025,0.95,0.06,2.43,0.26,8.86,High Risk
...,...,...,...,...,...,...,...
32060,33081,0.79,9.70,-8.84,0.20,9.89,High Risk
32061,33082,0.03,2.75,-2.52,0.67,0.85,High Risk
32062,33083,0.02,0.50,29.41,0.95,4.48,Moderate Risk
32063,33084,0.78,9.70,-6.95,0.41,9.19,High Risk
32064,33085,1.00,7.69,18.80,0.88,2.11,High Risk

In [58]:
df_risk.head(2)

,shipment_id,weather_severity,port_cong,iot_temp,cargo_status,route_risk,risk_class
0,1021,0.36,4.29,0.57,0.78,1.18,Moderate Risk
1,1022,0.23,7.02,-9.75,0.09,9.61,High Risk

In [59]:
df_warehouse.head(2)

,logistics_id,inventory_level_units,load_unload_hrs,equipment_availability_percent,supplier_reliability,lead_days,historical_demand_units,disruption_likelihood,delay_probability,customs_days
0,1021,985.72,4.95,0.48,0.99,2.13,100.77,0.51,0.89,0.50
1,1022,396.70,1.03,0.62,0.46,12.61,5313.74,0.98,0.54,0.97

In [60]:
df_transit.head(2)

,index,record_id,date,time,latitude,longitude,fuel_rate_usd,eta_vars_hrs,traffic_level,time_deviation,shipping_cost_usd,order_status
0,0,1021,2021-01-01,00:00:00,40.375568,-77.014318,5.14,5.00,5,9.11,456.50,0.76
1,1,1022,2021-01-01,01:00:00,33.507818,-117.036902,5.10,0.98,1,8.18,640.41,0.20

In [61]:
# 1. Sabhi tables ke ID columns ko standard 'record_id' naam de do
df_transit = df_transit.rename(columns={'id': 'record_id'}) # agar koi purani id ho
df_warehouse = df_warehouse.rename(columns={'logistics_id': 'record_id'})
df_risk = df_risk.rename(columns={'shipment_id': 'record_id'})

In [62]:
cols =[df_transit , df_warehouse, df_risk]

In [63]:
for i in cols:
    print (i.columns)
    print ('---------------------------------')

Index(['index', 'record_id', 'date', 'time', 'latitude', 'longitude',
       'fuel_rate_usd', 'eta_vars_hrs', 'traffic_level', 'time_deviation',
       'shipping_cost_usd', 'order_status'],
      dtype='str')
---------------------------------
Index(['record_id', 'inventory_level_units', 'load_unload_hrs',
       'equipment_availability_percent', 'supplier_reliability', 'lead_days',
       'historical_demand_units', 'disruption_likelihood', 'delay_probability',
       'customs_days'],
      dtype='str')
---------------------------------
Index(['record_id', 'weather_severity', 'port_cong', 'iot_temp',
       'cargo_status', 'route_risk', 'risk_class'],
      dtype='str')
---------------------------------

In [64]:
print(df_transit.time)

0        00:00:00
1        01:00:00
2        02:00:00
3        03:00:00
4        04:00:00
           ...
32060    20:00:00
32061    21:00:00
32062    22:00:00
32063    23:00:00
32064    00:00:00
Name: time, Length: 32065, dtype: object

In [65]:
df_risk.head()

,record_id,weather_severity,port_cong,iot_temp,cargo_status,route_risk,risk_class
0,1021,0.36,4.29,0.57,0.78,1.18,Moderate Risk
1,1022,0.23,7.02,-9.75,0.09,9.61,High Risk
2,1023,0.03,9.61,-6.49,0.25,6.57,High Risk
3,1024,0.62,8.90,-0.15,0.88,0.55,High Risk
4,1025,0.95,0.06,2.43,0.26,8.86,High Risk

In [66]:
df_risk.head(2)

,record_id,weather_severity,port_cong,iot_temp,cargo_status,route_risk,risk_class
0,1021,0.36,4.29,0.57,0.78,1.18,Moderate Risk
1,1022,0.23,7.02,-9.75,0.09,9.61,High Risk

In [67]:
df_transit.drop(columns ='index',inplace=True)

##### Create Connection for Neon(PostGreSQL)

In [72]:
from sqlalchemy import create_engine, text

DATABASE_URL = "postgresql://neondb_owner:npg_N4dJTH8mhlQD@ep-bitter-sound-b4c5yh81-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
engine = create_engine(DATABASE_URL)

# Pehle dependent/child tables clear karo taaki foreign key error na aaye
with engine.begin() as connection:
    connection.execute(text("TRUNCATE TABLE supply_chain_risk RESTART IDENTITY CASCADE;"))
    connection.execute(text("TRUNCATE TABLE supply_chain_transit RESTART IDENTITY CASCADE;"))
    connection.execute(text("TRUNCATE TABLE supply_chain_warehouse RESTART IDENTITY CASCADE;"))

# Ab naya modified dataframe upload kar do
df_transit.to_sql('supply_chain_transit', engine, if_exists='append', index=False)
df_warehouse.to_sql('supply_chain_warehouse', engine, if_exists='append', index=False)
df_risk.to_sql('supply_chain_risk', engine, if_exists='append', index=False)

print("Updated data successfully uploaded!")

Updated data successfully uploaded!